services:
  langfuse-worker:
    depends_on:
      langfuse-minio-migration:
        condition: service_healthy
    environment:
      LANGFUSE_S3_EVENT_UPLOAD_REGION: 'auto'
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_MIGRATION_MINIO_ACCESS_KEY:-minio}'
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_MIGRATION_MINIO_SECRET_KEY:-minio-local-secret}'
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: 'http://langfuse-minio-migration:9000'
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: 'true'
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: 'auto'
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_MIGRATION_MINIO_ACCESS_KEY:-minio}'
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_MIGRATION_MINIO_SECRET_KEY:-minio-local-secret}'
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: '${LANGFUSE_MINIO_MEDIA_ENDPOINT:-http://localhost:9190}'
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: 'true'

  langfuse-web:
    depends_on:
      langfuse-minio-migration:
        condition: service_healthy
    environment:
      LANGFUSE_S3_EVENT_UPLOAD_REGION: 'auto'
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_MIGRATION_MINIO_ACCESS_KEY:-minio}'
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_MIGRATION_MINIO_SECRET_KEY:-minio-local-secret}'
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: 'http://langfuse-minio-migration:9000'
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: 'true'
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: 'auto'
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_MIGRATION_MINIO_ACCESS_KEY:-minio}'
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_MIGRATION_MINIO_SECRET_KEY:-minio-local-secret}'
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: '${LANGFUSE_MINIO_MEDIA_ENDPOINT:-http://localhost:9190}'
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: 'true'
