package io.github.vfedoriv.graphrag.discovery;

public enum SourceFailureCode {
    TRANSPORT_TIMEOUT,
    TRANSPORT_IO,
    RATE_LIMIT,
    PROVIDER_RETRYABLE_STATUS,
    PROVIDER_5XX,
    PROVIDER_AUTH,
    PROVIDER_INVALID_REQUEST,
    PROVIDER_ERROR,
    EMPTY_MODEL_RESPONSE,
    MALFORMED_MODEL_RESPONSE,
    INVALID_MODEL_CANDIDATE,
    SOURCE_STALE,
    SOURCE_UNAVAILABLE,
    CONFIGURATION_ERROR
}
